### ISSUE TITLE
Update fvcore_layout.rc (input.nml) handling when model version is updated

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/GEOSadas#52]
Proactive note to remember an issue needed to be addressed as we move the model version forward from the initial 5_27_1 version.
From version 1.3.6+ the fvcore_layout.rc file has fields that must be filled out related to the hydrostatic/non-hydrostatic settings that are filled out by the gcm_setup script via user questions and/or resolution chosen.
In addition the fvcore_layout.rc file must be copied to the input.nml file.
The DAS scripts must be correspondingly be updated. This is necessary for both the mkiau.x and GEOSgcm.x to run.

The PR that brought this into the @GEOSgcm_App is here:
https://github.com/GEOS-ESM/GEOSgcm_App/commit/07a9759c2a57862138dcb88a12174db6022d038a#diff-15ae3cfecb3a30a98a4576d667160fb80a3f0e9e27fd9dd028d494080200a536

**Comment by rtodling** [comment]
Ben, 
The run and fcst directories in your experiment hold copies of the fvcore_layout.rc file. If you need to change these you can do then locally; ultimately these two files (presently identical) come from Applications/GEOSgcm_App.

Now, mkiau.x is different. It actually uses input.nml ... that is a dummy one; when mkiau.rc runs, the scripts touch a file named input.nml - this is done main job script g5das.j ... this will not affect the model since mkiau.x runs before gcm.x ... so mkiau.x sees a dummy input.nml ... then before calling gcm.x the scripts check for the existence of fvcore_layout.rc and link it to input.nml ... 

I hope this helps

**Comment by bena-nasa** [comment]
Hi Ricardo, I'm not seeing any reference to input.nml in the g5das.j I'm looking at.

**Comment by rtodling** [comment]
This is already done in 5.29.3 - I'm closing this.
